name 'formatron_chef_extra'
version '0.1.1'
description 'Formatron Chef extra cookbook'
source_url 'https://github.com/formatron/chef-extra-cookbook'
issues_url 'https://github.com/formatron/chef-extra-cookbook/issues'
supports 'ubuntu'
depends 'formatron_common'
