name 'formatron_chef_extra'
version '0.1.2'
description 'Formatron Chef extra cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/chef-extra-cookbook'
issues_url 'https://github.com/formatron/chef-extra-cookbook/issues'
supports 'ubuntu'
depends 'formatron_common'
